version: '3'
services: 
    app:
        container_name: microblog-restful-api-project
        restart: always
        build: .
        ports:
            - '8010:8010'
        links: 
            - mongo
    mongo:
        container_name: mongo-restful-api
        image: mongo
        ports: 
            - '27017:27017'